repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.5.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-yaml
      - id: check-added-large-files
      - id: check-toml
      - id: pretty-format-json
      - id: name-tests-test
        exclude: "(^.vscode/|.gitlab-ci.yml/_version.py)"

  - repo: https://github.com/psf/black
    rev: 24.3.0
    hooks:
      - id: black
